### PR TITLE
Updated node/nuget dependencies to support Fable 3.0

### PR DESCRIPTION
**Pull request by drk-mtr**
- Updated all node dependencies to latest versions (`package-lock.json` & `yarn.lock`)
- Updated nuget package versions i.e. `paket.lock`
- Updated nuget API source to v3 in `paket.dependencies`
- Added framework versions in `paket.dependencies`
- Removed references to `Fable.Import.Browser`
- Changed `Fable.Helpers.React` -> `Fable.React`
- Added `"corejs": "3"` parameter to `webpack.config.js` babel builtins

### CODE REVIEW

**Comment by drk-mtr** [comment]
It felt a bit silly not updating the demo project too, I'll try and do that too some time soon if you want it updated :)

**Comment by MangelMaxime** [comment]
Thank you @drk-mtr ,

the template has been published and can be used from nuget now

**Comment by drk-mtr** [comment]
Thanks! I've used a few of your projects and it makes it so much easier for a beginner like me to get up and running, hugely appreciate how generous you are with sharing stuff.

On my PC, I get an error when I run `npm start`:

    ERROR in ./src/App.fs
    Module build failed (from ./node_modules/fable-loader/index.js):
    Error: File D:/Coding/FableElmishReactTest/src/App.fs cannot be found in source list:
    D:/Coding/FableElmishReactTest/src/Global.fs
    D:/Coding/FableElmishReactTest/src/Counter/Types.fs
    D:/Coding/FableElmishReactTest/src/Counter/View.fs
    D:/Coding/FableElmishReactTest/src/Home/Types.fs
    D:/Coding/FableElmishReactTest/src/Home/State.fs
    D:/Coding/FableElmishReactTest/src/Home/View.fs
    D:/Coding/FableElmishReactTest/src/Types.fs (D:/Coding/FableElmishReactTest/src/App.fs)
        at D:\Coding\FableElmishReactTest\node_modules\fable-loader\index.js:98:22
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
    @ ./src/FableElmishReactTest.fsproj 1:0-25 1:0-25
    @ multi ./src/FableElmishReactTest.fsproj

This is easily resolved by doing a `paket restore` so I'm not sure whether this is just a local issue or whether we should add a suggestion to the readme. Apologies in advance if this is something I've messed up!

Tested on my mac and all working fine there.

**Comment by MangelMaxime** [comment]
Thank you for the kind words and thank you for confirming it's working :)

Yes, I had the same error that you had. It's because the old template were using an old version of paket which didn't understand the new frameworks.

**Pull request merged**
